name: My First Workflow
on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          name: Checkout the Main Repo

        - name: Multiple command in same Run Command
          run: |
               echo "My first Github Actions Workflow"
               ls -lrta
               cat README.md

        - name: Generate ASCI
          run: |
               cowsay -f dragon "Run for cover, I am a Dragon...RAWS" >> dragon.txt
               cat dragon.txt  





        # - name: List Files
        #   run: ls 

        # - name: Read file
        #   run: cat README.md

    # secont_job: 
    #     runs-on: ubuntu-latest
    #     steps:
    #       - uses: actions/checkout@v3
    #       - name: Second Job
    #         run: echo "This is second job"

    
