name: Asci Workflow
on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          name: Checkout the Main Repo
    
        - name: List Repo
          run: ls -lrta

        - name: Execute Shell Script
          run: |
            chmod +x ./ascii-script.sh 
            ./ascii-script.sh
    second_job:
          needs: first_job
          runs-on: ubuntu-latest
          steps:
          - name: Read into dragon.txt
            run: grep -i "dragon" dragon.txt
    third_job:
          needs: second_job
          runs-on: ubuntu-latest
          steps:
          - name: Read into dragon.txt
            run: cat dragon.txt  
          - name: Running deploy
            run: echo "Deploying"
