name: Asci Workflow
on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          name: Checkout the Main Repo
    
        - name: List Repo
          run: ls -lrta

        - name: Permission added for Shell
          run: chmod +x ./ascii-script.sh

        - name: Execute Shell Script
          run: ./ascii-script.sh
        